# Mappings are provided so that environment specific servers can be mapped more easily
mappings:
  sample-ms: http://localhost:8900
  authn-ms: http://localhost:8281
  authz-ms: http://localhost:8282 
  swagger-ms: http://localhost:8283
  gateway-ms: http://localhost:8910

authorization:
  endpoint: ${mappings.authz-ms}/authz
  refreshTokenPath: /refresh

jwks:
  path: /jwks
  source: ${mappings.authz-ms}/.well-known/jwks
  uri: ${mappings.gateway-ms}/jwks

http:
  defaultBodyLimit: 2048

allowedOrigins: "*"

routes:
- from: /v1
  to: ${mappings.swagger-ms}/v1
  exact: true
  protected: false 
  onlyGetJson: true
- from: /v1/hello
  to: ${mappings.sample-ms}/hello
  exact: true
  protected: false
- from: /v1/hello
  to: ${mappings.sample-ms}/hello
- from: /v1/secure/upload
  to: ${mappings.sample-ms}/s/upload
  limit: 10000000 
- from: /v1/secure
  to: ${mappings.sample-ms}/s 
- from: /v1/authn
  to: ${mappings.authn-ms}/authn
  protected: false 
  
---

spring.profiles: docker-compose

http:
  port: 80
  defaultBodyLimit: 2048

mappings:
  sample-ms: http://sample-ms
  authn-ms: http://authentication-ms
  authz-ms: http://authorization-ms
  swagger-ms: http://swagger-ms
  gateway-ms: http://gateway-ms

